# Generated by Django 3.2.6 on 2022-03-16 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_matcher_user_connections_+', through='matcher.Connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.FloatField()),
                ('suggested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='suggested_roommates',
            field=models.ManyToManyField(blank=True, related_name='_matcher_user_suggested_roommates_+', through='matcher.Suggestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
